image: node:latest

services:
  - mongo:latest

variables:
  MONGODB_URL: 'mongodb://mongo/app_name'

cache:
  paths:
    - node_modules/

test_async:
  script:
    - npm install
    - npm run ci_test